#!/bin/bash
# SPDX-FileCopyrightText: © 2026 Shaun Wilson
# SPDX-License-Identifier: MIT
set -eo pipefail
if [ -z "$VIRTUAL_ENV" ]; then
    source .venv/bin/activate
fi
cd docs/
if [[ "$1" == "" ]]; then
    pip install -r requirements.txt
fi
make html
